// components/Footer.vue
<template lang="html">
  <div class="">

    <footer class="bg-white" aria-labelledby="footer-heading">
      <div id="footer-heading" class="sr-only">Footer</div>
      <div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
        <div>
          <img class="-ml-4 lg:block h-32 w-auto" src="/illustrations/republique-francaise-logo.png" alt="Reva">
          <div class="space-y-8 xl:col-span-1">
            <p class="text-gray-500 text-base">
              REVA simplifie la VAE
            </p>
            <div class="flex flex-col sm:flex-row sm:space-x-6">
              <a href="#" class="font-bold">
                legifrance.gouv.fr
              </a>

              <a href="#" class="font-bold">
                gouvernement.fr
              </a>

              <a href="#" class="font-bold">
                service-public.fr
              </a>

              <a href="#" class="font-bold">
                data.gouv.fr
              </a>
            </div>
          </div>

          <div class="mt-12 flex flex-col sm:flex-row sm:gap-8 xl:col-span-2 border-t pt-6">

            <div class="sm:border-r pr-4">
              <a href="#">Plan du site</a>
            </div>
            <div class="sm:border-r pr-4">
              <a href="#">Accessibilité</a>
            </div>
            <div class="sm:border-r pr-4">
              <a href="#">Mentions légales</a>
            </div>
            <div class="sm:border-r pr-4">
              <a href="#">Données personnelles</a>
            </div>
            <div class="">
              <a href="#">Gestion des cookies</a>
            </div>

          </div>

        </div>
        <div class="pt-8">
          <p class="text-base text-gray-400 xl:text-center">
            <a class="underline" href="https://github.com/etalab/licence-ouverte/blob/master/LO.md" target="_blank">
              Sauf mention contraire, tous les textes de ce site sont sous licence etalab-2.0
            </a>
          </p>
        </div>
      </div>
    </footer>

  </div>
</template>

<script>
export default {
}
</script>

<style lang="css" scoped>
</style>

// packages/reva-candidate/src/components/footer/Footer.tsx
import Image from "next/image";
import Link from "next/link";

import fvaeLogo from "@public/fvae_logo.svg";

export const Footer = () => (
  <footer className="fr-footer" role="contentinfo" id="footer">
    <div className="fr-container">
      <div className="fr-footer__body">
        <div className="fr-footer__brand fr-enlarge-link">
          <p className="fr-logo">
            République
            <br /> Française
          </p>
          <Link
            title="Accueil - France VAE"
            href="/../"
            className="fr-footer__brand-link"
          >
            <Image
              className="fr-footer__logo"
              src={fvaeLogo}
              alt="France VAE"
              style={{ width: "225px", height: "auto" }}
            />
          </Link>
        </div>
        <div className="fr-footer__content">
          <p className="fr-footer__content-desc">
            France VAE est le portail officiel du service public qui vise à
            transformer la VAE avec nos partenaires.
          </p>
          <ul className="fr-footer__content-list">
            <li className="fr-footer__content-item">
              <a
                className="fr-footer__content-link"
                target="_blank"
                href="http://info.gouv.fr/"
                aria-label="gouvernement.fr nouvelle page"
              >
                info.gouv.fr
              </a>
            </li>
            <li className="fr-footer__content-item">
              <a
                className="fr-footer__content-link"
                target="_blank"
                href="https://service-public.fr"
                aria-label="service-public.fr nouvelle page"
              >
                service-public.fr
              </a>
            </li>
            <li className="fr-footer__content-item">
              <a
                className="fr-footer__content-link"
                target="_blank"
                href="https://legifrance.gouv.fr"
                aria-label="legifrance.gouv.fr nouvelle page"
              >
                legifrance.gouv.fr
              </a>
            </li>
            <li className="fr-footer__content-item">
              <a
                className="fr-footer__content-link"
                target="_blank"
                href="https://data.gouv.fr"
                aria-label="data.gouv.fr nouvelle page"
              >
                data.gouv.fr
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div className="fr-footer__bottom">
        <ul className="fr-footer__bottom-list">
          <li className="fr-footer__bottom-item">
            <Link
              className="fr-footer__bottom-link"
              href="/../declaration-accessibilite/"
            >
              Accessibilité : partiellement conforme
            </Link>
          </li>
          <li className="fr-footer__bottom-item">
            <Link className="fr-footer__bottom-link" href="/../cgu/">
              CGU
            </Link>
          </li>
          <li className="fr-footer__bottom-item">
            <Link
              className="fr-footer__bottom-link"
              href="/../mentions-legales/"
            >
              Mentions légales
            </Link>
          </li>
          <li className="fr-footer__bottom-item">
            <Link
              className="fr-footer__bottom-link"
              href="/../confidentialite/"
            >
              Données personnelles
            </Link>
          </li>
          <li className="fr-footer__bottom-item">
            <Link className="fr-footer__bottom-link" href="/../nous-contacter">
              Nous&nbsp;contacter
            </Link>
          </li>
        </ul>
        <div className="fr-footer__bottom-copy">
          <p className="mb-4">
            Sauf mention contraire, tous les contenus de ce site sont sous{" "}
            <Link
              href="https://github.com/etalab/licence-ouverte/blob/master/LO.md"
              target="_blank"
              aria-label="licence etalab-2.0 nouvelle page"
            >
              licence etalab-2.0
            </Link>
          </p>
        </div>
      </div>
    </div>
  </footer>
);
