// packages/reva-app/src/components/atoms/Checkbox/index.tsx
interface CheckboxProps {
  checked: boolean;
  /**
   * Checkbox name
   */
  name: string;
  /**
   * Checkbox label
   */
  label: string;
  /**
   * Custom class
   */
  className?: string;
  toggle: () => void;
}

export const Checkbox = ({
  checked,
  name,
  label,
  toggle,
  className = "",
  ...props
}: CheckboxProps) => {
  return (
    <div className="relative flex items-start">
      <div className="flex items-center h-[26px]">
        <input
          id={name}
          aria-describedby="comments-description"
          name={name}
          defaultChecked={checked}
          onClick={toggle}
          type="checkbox"
          className="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
        />
      </div>
      <div className="ml-3 text-lg">
        <label htmlFor={name} className="block text-slate-700 leading-snug">
          {label}
        </label>
      </div>
    </div>
  );
};

// components/Checkbox.vue
<template>
  <label class="relative border p-4 flex cursor-pointer focus:outline-none">
    <input
      :id="id"
      :checked="checked"
      :type="getType()"
      :value="id"
      class="
        h-4
        w-4
        mt-0.5
        cursor-pointer
        text-indigo-600
        border-gray-300
        focus:ring-indigo-500
        flex-none
      "
      :aria-describedby="id + '-description'"
      :aria-labelledby="id + '-label'"
      :name="name"
      @change="onChange()"
    />
    <div class="ml-3 flex flex-col">
      <!-- Checked: "text-indigo-900", Not Checked: "text-gray-900" -->
      <span :id="id + '-label'" class="block text-sm font-medium">
        {{ label }}
      </span>
      <!-- Checked: "text-indigo-700", Not Checked: "text-gray-500" -->
      <span id="id + '-description'" class="block text-sm text-gray-500">
        {{ description }}
      </span>
    </div>
  </label>
</template>

<script lang="ts">
import { defineComponent, toRefs } from '@nuxtjs/composition-api'

export default defineComponent({
  props: {
    checked: {
      type: Boolean,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    id: {
      type: String,
      required: true,
    },
    label: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      default: '',
    },
    isMulti: {
      type: Boolean,
      default: () => false,
    },
  },

  setup(props, { emit }) {
    const { isMulti } = toRefs(props)
    return {
      getType() {
        return isMulti.value ? 'checkbox' : 'radio'
      },
      onChange() {
        emit('change')
      },
    }
  },
})
</script>
